### ISSUE TITLE
logo updated

### ISSUE THREAD

**Issue by niklasf** [rubenwardy/lichess_widgets#2]
upstream issue: https://github.com/ornicar/lila/issues/5680

announcement: https://lichess.org/blog/XeRN0BAAACAA7HJu/a-new-logo-for-lichess

new files: https://github.com/ornicar/lila/tree/master/public/logo hosted at https://lichess1.org/assets/logo/lichess-favicon-32.png etc.

**Comment by rubenwardy** [comment]
Huh, I completely missed this issue somehow. I'll get on it

**Comment by nimishbongale** [comment]
Can I try resolving this?
